# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 559f3c713a02340df35e82905f506829f38446ed669757590bc0eb0b53695afb28e70f4ceb2d684dd8ba45066a17fc7f82a55e9fa06bf70b8db5ecbe6505dbee

test:
  secret_key_base: b884bfb408847fe72e712fcf527006956eb81ea900a41424c715e4fe2f9a0f4f845493541721c8fe56c0f5d7ae58beb68a6b272427c0525a47af82415528fda6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
